### PR TITLE
some quick hack demo (DO NOT MERGE)

### PR DESCRIPTION
**Pull request by sidazhang**
@taariq @lkang 

Check out this branch and have a play:
run `$ node index.js`

you should see something like this:

```
1. Generate a hd wallet with a seed
2. Generate an address from the hd wallet:
3. Withdraw some Bitcoins to the address that we just generated:  mw43rS7LaXgCYXbjnrk5qgGpSqvYoLWwkg (so that we have some bitcoins to play with)
4. Load up the unspents into wallet
5. Now Send some money to a random address:mkmrA6fjVpneaFyvxbjbZM6w6TASG6zyjQ
6. Success! Now check out the transaction that we just sent from our bitcoin wallet: 

https://test.helloblock.io/transactions/d59b2393aadf89bdf2d475bee633ba5ff8423dae919d42d32b0ff31b605a9677
```

There is literally nothing simpler than this.

### CODE REVIEW

**Comment by taariq** [comment]
Worked. Very nice and very cool. True automated money routing! Let's show this off tomorrow!

**Comment by lkang** [comment]
vcool, thx!

**Comment by sidazhang** [comment]
I think, we can have all the bitcoin related code here and then provide a set of apis for the front end repo to call.

For example:

c8.getAddresses() {} -> this displays a list of addresses and also makes an api call to get their respective balances

thoughts?

**Comment by taariq** [comment]
I thought this was perfect. let¹s go with it.

Apologies for the delay, but I¹m excited to move this forward.
‹
Thanks,
taariq.lewis@gmail.com
Schedule a bitcoin chat with me:  meetme.so/taariq http://meetme.so/taariq

From:  sidazhang notifications@github.com
Reply-To:  SF-Bitcoindevs/c8
<reply+i-31427494-c117f1aac26921f3eea74101c2135d98d55f4f65-701864@reply.gith
ub.com>
Date:  Sunday, April 13, 2014 at 11:07 PM
To:  SF-Bitcoindevs/c8 c8@noreply.github.com
Cc:  Taariq Lewis taariq.lewis@gmail.com
Subject:  Re: [c8] some quick hack demo (DO NOT MERGE) (#1)

I think, we can have all the bitcoin related code here and then provide a
set of apis for the front end repo to call.

For example:

c8.getAddresses() {} -> this displays a list of addresses and also makes an
api call to get their respective balances

thoughts?

‹
Reply to this email directly or view it on GitHub
https://github.com/SF-Bitcoindevs/c8/pull/1#issuecomment-40335602 .

**Comment by hackmistress69** [comment]
E1DBADA0-9C8C-4F9A-8265-5EC012AF1152

**Comment by taariq** [comment]
It's been a long time. Let's close this and archive.

**Pull request closed without merging**
